//! # Lavendeux VM
//! This module contains the Lavendeux VM and its components.
//! The VM is responsible for executing the bytecode generated by the compiler.
//! It also contains the memory manager which is responsible for storing values and functions

mod load_stdlib;

mod value_source;
pub use value_source::ValueSource;

pub mod error;
pub mod memory_manager;

mod execution_context;
pub use execution_context::ExecutionContext;

mod opcodes;
pub use opcodes::OpCode;
