//! # Lavendeux VM
//! This module contains the Lavendeux VM and its components.
//! The VM is responsible for executing the bytecode generated by the compiler.
//! It also contains the memory manager which is responsible for storing values and functions

mod execution_context;
mod load_stdlib;

pub mod error;
pub mod memory_manager;
pub mod value_source;

mod virtual_machine;
pub use virtual_machine::VirtualMachine;

mod opcodes;
pub use opcodes::OpCode;
